veterinaryapp/config/routes.rb
Rails.application.routes.draw do
  root   'dashboard#index'

  resources :appointments
  resources :pets
  resources :doctors
  resources :customers

end

veterinaryapp/app/models/appointment.rb
class Appointment < ActiveRecord::Base

has_one :doctor, foreign_key: 'id'


  validates :date, presence: true
  validate :date_in_past , :on => :create
  validates :pet, presence: true
  validates :customer, presence: true
  validates :reason, presence: true

 private

  def date_in_past
    if date < Date.today
      self.errors.add(:base, "The date you have selected is in the past!")
    end
  end

end

veterinaryapp/app/models/doctor.rb
class Doctor < ActiveRecord::Base
has_many :appointments

  validates :name, presence: true,
            length: {maximum: 35}

  validates_length_of :zip, :maximum => 5
end

veterinaryapp/app/models/pet.rb
class Pet < ActiveRecord::Base

  has_one :typeofpet, primary_key: "typeofpet_id", foreign_key: "id"
  has_many :appointments, primary_key: "appointmnet_id", foreign_key: "id"

  validates :name, presence: true
  validates :breed, presence: true
  validates :age, presence: true
  validates :weight, presence: true
  validates :lastvisit, presence: true
end

veterinaryapp/app/models/typeofpet.rb
class Typeofpet < ActiveRecord::Base
  belongs_to :pet
end

veterinaryapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

veterinaryapp/app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
	  before_action :set_appointment, only: [:show, :edit, :update, :destroy]
  def index
    @appointments = Appointment.all
  end
  
  def show
  end
  
  def customer
    @appointments = Appointment.all
  end
  
  def new
    @appointment = Appointment.new
  end
  
  def edit
  end

  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
   
  private
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    def appointment_params
      params.require(:appointment).permit(:doctor_id, :date, :customer, :pet, :reminder, :reason )
    end
end

veterinaryapp/app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  def index
    @appointments = Appointment.all
  end

end

veterinaryapp/app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

veterinaryapp/app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController 
	before_action :set_doctor, only: [:show, :edit, :update, :destroy]

    def index
      @doctors = Doctor.all
    end

    def show
    end

    def new
      @doctor = Doctor.new
    end

    def edit
    end

    def create
      @doctor = Doctor.new(appointment_params)

      respond_to do |format|
        if @doctor.save
          format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
          format.json { render :show, status: :created, location: @doctor }
        else
          format.html { render :new }
          format.json { render json: @doctor.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @doctor.update(appointment_params)
          format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
          format.json { render :show, status: :ok, location: @doctor }
        else
          format.html { render :edit }
          format.json { render json: @doctor.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @doctor.destroy
      respond_to do |format|
        format.html { redirect_to appointments_url, notice: 'Doctor was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
    
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    def appointment_params
      params.require(:doctor).permit(:name, :address, :city, :state, :zip, :school, :years)
    end
end

veterinaryapp/app/controllers/pets_controller.rb
class PetsController < ApplicationController
	 before_action :set_pet, only: [:show, :edit, :update, :destroy]

  def index
    @pets = Pet.all
  end
  
  def show
  end

  def new
    @pet = Pet.new
  end

  def edit
  end

  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_pet
      @pet = Pet.find(params[:id])
    end

    def pet_params
      params.require(:pet).permit(:name, :typeofpet_id, :breed, :age, :weight, :lastvisit)
    end

end

veterinaryapp/app/helpers/application_helper.rb
module ApplicationHelper
end

veterinaryapp/app/helpers/appointments_helper.rb
module AppointmentsHelper
end

veterinaryapp/app/helpers/customers_helper.rb
module CustomersHelper
end

veterinaryapp/app/helpers/dashboard_helper.rb
module DashboardHelper
end

veterinaryapp/app/helpers/doctors_helper.rb
module DoctorsHelper
end

veterinaryapp/app/helpers/pets_helper.rb
module PetsHelper
end

veterinaryapp/app/views/appointments/_form.html.erb
<%= form_for(@appointment,:html => { :class =>"form-horizontal" }) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="panel panel-primary">
      <div class="panel-heading"><h3>Appointment Details</h3></div>
      <div class="panel-body">

        <div class="form-group">
          <%= f.label :doctor_id, "Doctor's Name:", class: 'control-label col-sm-2' %>
          <div class="col-sm-4">
            <%=f.collection_select :doctor_id,  Doctor.order(:name),:id, :name, {}, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :date, "Date of Visit:", class: 'control-label col-sm-2' %>
          <div class="col-sm-4">
            <%=f.date_select :date,  class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :pet, "Pet's Name:", class: 'control-label col-sm-2' %>
          <div class="col-sm-4">
            <%=f.text_field :pet,  :placeholder => "Pet's Name", class: 'form-control' %>
          </div>
        </div>
          <div class="form-group">
            <%= f.label :customer, "Customer's Name:", class: 'control-label col-sm-2' %>
            <div class="col-sm-4">
              <%=f.text_field :customer,:placeholder => "Customer's Name", class: 'form-control' %>
            </div>
          </div>
            <div class="form-group">
              <%= f.label :reminder, "Requires Reminder:", class: 'control-label col-sm-2' %>
              <div class="col-sm-4">
                <%=f.check_box :reminder%>
              </div>
            </div>

      <div class="form-group">
        <%= f.label :reason, "Reason for Visit:", class: 'control-label col-sm-2' %>
        <div class="col-sm-4">
          <%=f.text_area :reason,  class: 'form-control',  :rows => "6" %>
         </div>
      </div>

    </div>



        </div>
         <div style="text-align: center; margin-left:auto; margin-right: auto">
           <%= f.submit "Submit", :class=> 'btn btn-primary' %>
        </div>
<% end %>

veterinaryapp/app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form' %>

  <div style="text-align: center;margin-left: auto;margin-right: auto"><br>
<%= link_to 'Show', @appointment, class: 'btn btn-primary' %>
<%= link_to 'Back', appointments_path, class: 'btn btn-primary' %>
</div>

veterinaryapp/app/views/appointments/index.html.erb
<p id="notice"><%= notice %></p>


<div class="panel panel-primary">
  <div class="panel-heading"><h3>Appointment Listing</h3></div>
  <div class="panel-body">
    <table border="1" style="width:100%">
      <thead>
      <tr>
        <th colspan="3">Date of Visit</th>
        <th colspan="3">Doctor's Name</th>
        <th colspan="3">Pet Name</th>
        <th colspan="3">Customer Name</th>
        <th colspan="3">Requires Reminder</th>
        <th colspan="3">Reason for Visit</th>
        <th colspan="3" style="text-align: center;">View</th>
        <th colspan="3" style="text-align: center;">Edit</th>
        <th colspan="3" style="text-align: center;">Delete</th>

      </tr>
      </thead>

      <tbody>
      <% @appointments.each do |ap| %>
          <tr>
            <td colspan="3"><%=ap.date.to_s(:long) %></td>
            <td colspan="3"><%=ap.doctor.name %></td>
            <td colspan="3"><%=ap.pet %></td>
            <td colspan="3"><%=ap.customer %></td>

              <% if ap.reminder  %>
                 <td colspan="3">Yes</td>
                <%else%>
                    <td colspan="3">No</td>
                <%end%>

            <td colspan="3"><%=ap.reason %></td>

            <td colspan="3" style="text-align: center;"><%= link_to ap do %>
                  <span class="glyphicon glyphicon-search"></span>
              <% end %></td>
            <td colspan="3" style="text-align: center;"><%= link_to edit_appointment_path(ap.id) do %> <span class="glyphicon glyphicon-pencil"></span>
              <% end %></td>
            <td colspan="3" style="text-align: center;"><%= link_to  ap, method: :delete, data: { confirm: 'Are you sure?' } do %> <span class="glyphicon glyphicon-trash"></span>
              <% end %></td>
          </tr>
      <% end %>
      </tbody>
    </table>

</div>
  </div>
<br>

<div style="text-align: center;margin-left: auto;margin-right: auto">
<%= link_to 'New Appointment', new_appointment_path,  :class=> 'btn btn-primary' %>

</div>

veterinaryapp/app/views/appointments/index.json.jbuilder.erb
json.array!(@appointments) do |appointment|
  json.extract! appointment, :id
  json.url appointment_url(appointment, format: :json)
end

veterinaryapp/app/views/appointments/new.html.erb
<h1>Create Appointment</h1>

<%= render 'form' %>
<br>
<div style="text-align: center;margin-left: auto;margin-right: auto">
<%= link_to 'Back', appointments_path, :class=> 'btn btn-primary' %>
</div>

veterinaryapp/app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-primary">
  <div class="panel-heading"><h3>Appointment Details</h3></div>
  <div class="panel-body">
    <table class="table table-striped table-bordered" cellspacing="0" width="50%">

      <tbody>

      <tr><td><strong>Appointment Date:</strong> </td><td><%= @appointment.date.to_s(:long) %></td></tr>
      <tr><td><strong>Pet's Name:</strong> </td><td><%= @appointment.pet %></td></tr>
      <tr><td><strong>Customer's Name:</strong> </td><td><%= @appointment.customer %></td></tr>
      <tr><td><strong>Requires Reminder:</strong> </td><td><%= @appointment.reminder %></td></tr>
      <tr><td><strong>Reason for Visit:</strong> </td><td><%= @appointment.reason %></td></tr>

      </tbody>
    </table>

  </div>
</div>

<div style="text-align: center;margin-left: auto;margin-right: auto">

<%= link_to 'Edit', edit_appointment_path(@appointment), :class=> 'btn btn-primary' %>
<%= link_to 'Back', appointments_path, :class=> 'btn btn-primary' %>
</div>

veterinaryapp/app/views/appointments/show.json.jbuilder.erb
json.extract! @appointment, :id, :created_at, :updated_at

veterinaryapp/app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>


<div class="panel panel-primary">
  <div class="panel-heading"><h3>Appointment Listing</h3></div>
  <div class="panel-body">
    <table border="1" style="width:100%">
      <thead>
      <tr>
        <th colspan="3">Customer Name</th>
        <th colspan="3">Date of Next Appointmnet</th>
        <th colspan="3">Pet Name</th>
        <th colspan="3">Reason for Visit</th>


      </tr>
      </thead>

      <tbody>
      <% @appointments.each do |ap| %>
          <tr>
            <td colspan="3"><%=ap.customer %></td>
            <td colspan="3"><%=ap.date.to_s(:long) %></td>
            <td colspan="3"><%=ap.pet %></td>
            <td colspan="3"><%=ap.reason %></td>

          </tr>
      <% end %>
      </tbody>
    </table>

  </div>
</div>
<br>

veterinaryapp/app/views/doctors/_form.html.erb
<%= form_for(@doctor,:html => { :class =>"form-horizontal" }) do |f| %>
  <% if @doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% @doctor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


        <div class="panel panel-primary">
          <div class="panel-heading"><h3>Doctor Details</h3></div>
          <div class="panel-body">

            <div class="form-group">
                  <%= f.label :name, "Doctor's Name:", class: 'control-label col-sm-2' %>
                  <div class="col-sm-4">
                    <%=f.text_field :name,  :placeholder => "Doctor's Name", class: 'form-control', :maxlength=> 35 %>
                  </div>
            </div>


            <div class="form-group">
              <%= f.label :name, "Address:", class: 'control-label col-sm-2' %>
              <div class="col-sm-4">
                <%=f.text_field :address,  :placeholder => "Address", class: 'form-control' %>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :city, "City:", class: 'control-label col-sm-2' %>
              <div class="col-sm-4">
                <%=f.text_field :city,  :placeholder => "City", class: 'form-control' %>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :state, "State:", class: 'control-label col-sm-2' %>
              <div class="col-sm-4">
                <%=f.text_field :state,  :placeholder => "State", class: 'form-control' %>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :zip, "Zip:", class: 'control-label col-sm-2' %>
              <div class="col-sm-4">
                <%=f.text_field :zip,  :placeholder => "Zip", class: 'form-control', :maxlength=> 5 %>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :school, "School Received Degree From:", class: 'control-label col-sm-2' %>
              <div class="col-sm-4">
                <%=f.text_field :school,  :placeholder => "School Received Degree From", class: 'form-control' %>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :years, "Years in Practice:", class: 'control-label col-sm-2' %>
              <div class="col-sm-4">
                <%=f.number_field :years,   in: 1...101,  :placeholder => "Years in Practice", class: 'form-control' %>
              </div>
            </div>





          </div>



        </div>

      <div style="text-align: center;margin-left: auto;margin-right: auto">
        <%= f.submit "Submit", :class=> 'btn btn-primary' %>
      </div>
<% end %>

veterinaryapp/app/views/doctors/edit.html.erb
<h1>Editing Doctor</h1>

<%= render 'form' %>

<br>
  <div style="text-align: center;margin-left: auto;margin-right: auto">

    <%= link_to 'Show', @doctor, class: 'btn btn-primary'  %>
    <%= link_to 'Back', doctors_path , class: 'btn btn-primary' %>
  </div>

veterinaryapp/app/views/doctors/index.html.erb
<p id="notice"><%= notice %></p>


<div class="panel panel-primary">
  <div class="panel-heading"><h3>Doctor Listing</h3></div>
  <div class="panel-body">
<table border="1" style="width:100%">
  <thead>
    <tr>
      <th colspan="3">Name</th>
      <th colspan="3">Address</th>
      <th colspan="3">City</th>
      <th colspan="3">State</th>
      <th colspan="3">Zip</th>
      <th colspan="3">Degree From</th>
      <th colspan="3">Years</th>
      <th colspan="3" style="text-align: center;">View</th>
      <th colspan="3" style="text-align: center;">Edit</th>
      <th colspan="3" style="text-align: center;">Delete</th>

    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |d| %>
      <tr>
        <td colspan="3"><%=d.name %></td>
        <td colspan="3"><%=d.address %></td>
        <td colspan="3"><%=d.city %></td>
        <td colspan="3"><%=d.state %></td>
        <td colspan="3"><%=d.zip %></td>
        <td colspan="3"><%=d.school %></td>
        <td colspan="3"><%=d.years %></td>
        <td colspan="3" style="text-align: center;"><%= link_to d do %>
              <span class="glyphicon glyphicon-search"></span>
          <% end %></td>
        <td colspan="3" style="text-align: center;"><%= link_to edit_doctor_path(d.id) do %> <span class="glyphicon glyphicon-pencil"></span>
          <% end %></td>
        <td colspan="3" style="text-align: center;"><%= link_to  d, method: :delete, data: { confirm: 'Are you sure?' } do %> <span class="glyphicon glyphicon-trash"></span>
          <% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div></div>

  <div style="text-align: center;margin-left: auto;margin-right: auto">
<%= link_to 'New Doctor', new_doctor_path, class: 'btn btn-primary' %>
</div></div>

veterinaryapp/app/views/doctors/index.json.jbuilder.erb
json.array!(@doctors) do |doctor|
  json.extract! doctor, :id
  json.url doctor_url(doctor, format: :json)
end

veterinaryapp/app/views/doctors/new.html.erb
<h1>New Doctor</h1>
<div class="container">
<%= render 'form' %>
<br>
<div style="text-align: center;margin-left: auto;margin-right: auto">
<%= link_to 'Back', doctors_path,  :class=> 'btn btn-primary' %>

</div>

</div>

veterinaryapp/app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>

  <div class="panel panel-primary">
    <div class="panel-heading"><h3><%= @doctor.name + "'s" %> Details</h3></div>
    <div class="panel-body">
      <table class="table table-striped table-bordered" cellspacing="0" width="50%">

        <tbody>

        <tr><td><strong>Doctor's Name:</strong> </td><td><%= @doctor.name %></td></tr>
        <tr><td><strong>Doctor's Address:</strong> </td><td><%= @doctor.address %></td></tr>
        <tr><td><strong>Doctor's City:</strong> </td><td><%= @doctor.city %></td></tr>
        <tr><td><strong>Doctor's State:</strong> </td><td><%= @doctor.state %></td></tr>
        <tr><td><strong>Doctor's Zip:</strong> </td><td><%= @doctor.zip %></td></tr>
        <tr><td><strong>School Received Degree From:</strong> </td><td><%= @doctor.school %></td></tr>
        <tr><td><strong>Years in Practice:</strong> </td><td><%= @doctor.years %></td></tr>
      </tbody>
      </table>

      </div>
    </div>


    <div style="text-align: center;margin-left: auto;margin-right: auto">
<%= link_to 'Edit', edit_doctor_path(@doctor), :class=> 'btn btn-primary' %>
<%= link_to 'Back', doctors_path, :class=> 'btn btn-primary' %>
</div>
</div>

veterinaryapp/app/views/doctors/show.json.jbuilder.erb
json.extract! @doctor, :id, :created_at, :updated_at

veterinaryapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VeterinaryApplication</title>
 <%= csrf_meta_tags %>
</head>
<body>
<div>
  <a href=<%= root_path %>>Home</a>
</div>
  <div>
    <ul>
      <li><a href=<%= doctors_path %>>Owner</a></li>
      <li><a href=<%= pets_path %>>Doctor</a></li>
      <li><a href=<%= appointments_path %>>Receptionist</a></li>
      <li><a href=<%= customers_path %>>Customer</a></li>

    </ul>
  </div>
  </nav>

<div id="main-container" class="container">
  <%= yield %>
</div>

</div>



</body>
</html>

veterinaryapp/app/views/pets/_form.html.erb
<%= form_for(@pet,:html => { :class =>"form-horizontal" }) do |f| %>
  <% if @pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% @pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="panel panel-primary">
      <div class="panel-heading"><h3>Pet Details</h3></div>
      <div class="panel-body">

        <div class="form-group">
          <%= f.label :name, "Pet Name", class: 'control-label col-sm-2' %>
          <div class="col-sm-4">
            <%=f.text_field :name,  :placeholder => "Pet Name", class: 'form-control', :maxlength=> 35 %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :typeofpet_id, "Tyoe of Pet:", class: 'control-label col-sm-2' %>
          <div class="col-sm-4">
            <%=f.collection_select :typeofpet_id,  Typeofpet.order(:name),:id, :name, {}, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :breed, "Breed:", class: 'control-label col-sm-2' %>
          <div class="col-sm-4">
            <%=f.text_field :breed,  :placeholder => "Breed", class: 'form-control', :maxlength=> 35 %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :age, "Age:", class: 'control-label col-sm-2' %>
          <div class="col-sm-4">
            <%=f.text_field :age,  :placeholder => "Age", class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :weight, "Weight:", class: 'control-label col-sm-2' %>
          <div class="col-sm-4">
            <%=f.text_field :weight,  :placeholder => "Weight", class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :lastvisit, "Date of Last Visit:", class: 'control-label col-sm-2' %>
          <div class="col-sm-4">
            <%=f.date_select :lastvisit,  class: 'form-control' %>
          </div>
        </div>





      </div>



    </div>
    <div style="text-align: center;margin-left: auto;margin-right: auto">

    <%= f.submit "Submit", :class=> 'btn btn-primary' %>
  </div>
<% end %>

veterinaryapp/app/views/pets/edit.html.erb
<h1>Editing Pet</h1>

<%= render 'form' %><br>
<div style="text-align: center;margin-left: auto;margin-right: auto">
<%= link_to 'Show', @pet, :class=> 'btn btn-primary' %>
<%= link_to 'Back', pets_path, :class=> 'btn btn-primary' %>
</div>

veterinaryapp/app/views/pets/index.html.erb
<p id="notice"><%= notice %></p>



<div>
  <div><h3>Pet Records Listing</h3></div>
  <div>
    <table border="1" style="width:100%">
      <thead>
      <tr>

        <th colspan="3">Pet Name</th>
        <th colspan="3">Type of Pet</th>
        <th colspan="3">Breed</th>
        <th colspan="3">Age</th>
        <th colspan="3">Weight</th>
        <th colspan="3">Date of Last Visit</th>
        <th colspan="3" style="text-align: center;">View</th>
        <th colspan="3" style="text-align: center;">Edit</th>
        <th colspan="3" style="text-align: center;">Delete</th>

      </tr>
      </thead>

      <tbody>
      <% @pets.each do |p| %>
          <tr>
            <td colspan="3"><%=p.name %></td>
            <td colspan="3"><%=p.typeofpet.name %></td>
            <td colspan="3"><%=p.breed %></td>
            <td colspan="3"><%=p.age %></td>
            <td colspan="3"><%=p.weight %></td>
            <td colspan="3"><%=p.lastvisit.to_s(:long) %></td>
            <td colspan="3" style="text-align: center;"><%= link_to p do %>
                                                         <span class="glyphicon glyphicon-search"></span>
                                                        <% end %></td>
            <td colspan="3" style="text-align: center;"><%= link_to edit_pet_path(p.id) do %> <span class="glyphicon glyphicon-pencil"></span>
              <% end %></td>
            <td colspan="3" style="text-align: center;"><%= link_to  p, method: :delete, data: { confirm: 'Are you sure?' } do %> <span class="glyphicon glyphicon-trash"></span>
              <% end %></td>
          </tr>
      <% end %>
      </tbody>
    </table>

  </div>
</div>
<br>

<div style="text-align: center;margin-left: auto;margin-right: auto">
  <%= link_to 'New Pet Record', new_pet_path,  :class=> 'btn btn-primary' %>
</div>

veterinaryapp/app/views/pets/index.json.jbuilder.erb
json.array!(@pets) do |pet|
  json.extract! pet, :id
  json.url pet_url(pet, format: :json)
end

veterinaryapp/app/views/pets/new.html.erb
<h1>New Pet Record</h1>

<%= render 'form' %><br>
<div style="text-align: center;margin-left: auto;margin-right: auto">
<%= link_to 'Back', pets_path, :class => 'btn btn-primary' %>
</div>

veterinaryapp/app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-primary">
  <div class="panel-heading"><h3>Pet Details</h3></div>
  <div class="panel-body">
    <table class="table table-striped table-bordered" cellspacing="0" width="50%">

      <tbody>

      <tr><td><strong>Pet Name:</strong> </td><td><%= @pet.name %></td></tr>
      <tr><td><strong>Type of Pet:</strong> </td><td><%= @pet.typeofpet.name %></td></tr>
      <tr><td><strong>Breed:</strong> </td><td><%= @pet.breed %></td></tr>
      <tr><td><strong>Age:</strong> </td><td><%= @pet.age %></td></tr>
      <tr><td><strong>Weight:</strong> </td><td><%= @pet.weight %></td></tr>
      <tr><td><strong>Last Visit:</strong> </td><td><%=  @pet.lastvisit.to_s(:long) %></td></tr>
      </tbody>

    </table>

  </div>
</div>

<div style="text-align: center;margin-left: auto;margin-right: auto">

  <%= link_to 'Edit', edit_pet_path(@pet), :class=> 'btn btn-primary' %>
  <%= link_to 'Back', pets_path, :class=> 'btn btn-primary' %>
</div>

veterinaryapp/app/views/pets/show.json.jbuilder.erb
json.extract! @pet, :id, :created_at, :updated_at